OPENAI_MODEL="gpt-3.5-turbo"
TOGETHER_MODEL="mistralai/Mixtral-8x7B-Instruct-v0.1"
GOOGLE_MODEL="gemini-pro"
OPENROUTER_MODEL="nousresearch/nous-hermes-2-mixtral-8x7b-dpo"

"""
As of 2-7-2024
models from openrouter:
nousresearch/nous-capybara-34b
openrouter/auto
nousresearch/nous-capybara-7b:free
mistralai/mistral-7b-instruct:free
gryphe/mythomist-7b:free
undi95/toppy-m-7b:free
openrouter/cinematika-7b:free
jondurbin/bagel-34b
jebcarter/psyfighter-13b
koboldai/psyfighter-13b-2
neversleep/noromaid-mixtral-8x7b-instruct
nousresearch/nous-hermes-llama2-13b
meta-llama/codellama-34b-instruct
phind/phind-codellama-34b
intel/neural-chat-7b
nousresearch/nous-hermes-2-mixtral-8x7b-dpo
nousresearch/nous-hermes-2-mixtral-8x7b-sft
haotian-liu/llava-13b
nousresearch/nous-hermes-2-vision-7b
meta-llama/llama-2-13b-chat
gryphe/mythomax-l2-13b
nousresearch/nous-hermes-llama2-70b
nousresearch/nous-capybara-7b
codellama/codellama-70b-instruct
teknium/openhermes-2-mistral-7b
teknium/openhermes-2.5-mistral-7b
undi95/remm-slerp-l2-13b
undi95/toppy-m-7b
openrouter/cinematika-7b
01-ai/yi-34b-chat
01-ai/yi-34b
01-ai/yi-6b
togethercomputer/stripedhyena-nous-7b
togethercomputer/stripedhyena-hessian-7b
mistralai/mixtral-8x7b
nousresearch/nous-hermes-yi-34b
open-orca/mistral-7b-openorca
huggingfaceh4/zephyr-7b-beta
openai/gpt-3.5-turbo
openai/gpt-3.5-turbo-0125
openai/gpt-3.5-turbo-1106
openai/gpt-3.5-turbo-0613
openai/gpt-3.5-turbo-0301
openai/gpt-3.5-turbo-16k
openai/gpt-4-turbo-preview
openai/gpt-4-1106-preview
openai/gpt-4
openai/gpt-4-0314
openai/gpt-4-32k
openai/gpt-4-32k-0314
openai/gpt-4-vision-preview
openai/gpt-3.5-turbo-instruct
google/palm-2-chat-bison
google/palm-2-codechat-bison
google/palm-2-chat-bison-32k
google/palm-2-codechat-bison-32k
google/gemini-pro
google/gemini-pro-vision
perplexity/pplx-70b-online
perplexity/pplx-7b-online
perplexity/pplx-7b-chat
perplexity/pplx-70b-chat
meta-llama/llama-2-70b-chat
jondurbin/airoboros-l2-70b
austism/chronos-hermes-13b
migtissera/synthia-70b
mistralai/mistral-7b-instruct
pygmalionai/mythalion-13b
undi95/remm-slerp-l2-13b-6k
xwin-lm/xwin-lm-70b
gryphe/mythomax-l2-13b-8k
openchat/openchat-7b
alpindale/goliath-120b
lizpreciatior/lzlv-70b-fp16-hf
neversleep/noromaid-20b
gryphe/mythomist-7b
mistralai/mixtral-8x7b-instruct
cognitivecomputations/dolphin-mixtral-8x7b
rwkv/rwkv-5-world-3b
recursal/rwkv-5-3b-ai-town
recursal/eagle-7b
anthropic/claude-2
anthropic/claude-2.0
anthropic/claude-instant-v1
anthropic/claude-v1
anthropic/claude-1.2
anthropic/claude-instant-v1-100k
anthropic/claude-v1-100k
anthropic/claude-instant-1.0
huggingfaceh4/zephyr-7b-beta:free
openchat/openchat-7b:free
mancer/weaver
mistralai/mistral-tiny
mistralai/mistral-small
mistralai/mistral-medium

models at together ai:
Austism/chronos-hermes-13b
DiscoResearch/DiscoLM-mixtral-8x7b-v2
Gryphe/MythoMax-L2-13b
Meta-Llama/Llama-Guard-7b
Nexusflow/NexusRaven-V2-13B
NousResearch/Nous-Capybara-7B-V1p9
NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO
NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT
NousResearch/Nous-Hermes-2-Yi-34B
NousResearch/Nous-Hermes-Llama2-13b
NousResearch/Nous-Hermes-llama-2-7b
Open-Orca/Mistral-7B-OpenOrca
Phind/Phind-CodeLlama-34B-v2
Qwen/Qwen1.5-0.5B-Chat
Qwen/Qwen1.5-0.5B
Qwen/Qwen1.5-1.8B-Chat
Qwen/Qwen1.5-1.8B
Qwen/Qwen1.5-14B-Chat
Qwen/Qwen1.5-14B
Qwen/Qwen1.5-4B-Chat
Qwen/Qwen1.5-4B
Qwen/Qwen1.5-72B-Chat
Qwen/Qwen1.5-72B
Qwen/Qwen1.5-7B-Chat
Qwen/Qwen1.5-7B
SG161222/Realistic_Vision_V3.0_VAE
Undi95/ReMM-SLERP-L2-13B
Undi95/Toppy-M-7B
WizardLM/WizardCoder-15B-V1.0
WizardLM/WizardCoder-Python-34B-V1.0
WizardLM/WizardLM-13B-V1.2
codellama/CodeLlama-13b-Instruct-hf
codellama/CodeLlama-13b-Python-hf
codellama/CodeLlama-34b-Instruct-hf
codellama/CodeLlama-34b-Python-hf
codellama/CodeLlama-70b-Instruct-hf
codellama/CodeLlama-70b-Python-hf
codellama/CodeLlama-70b-hf
codellama/CodeLlama-7b-Instruct-hf
codellama/CodeLlama-7b-Python-hf
lmsys/vicuna-13b-v1.5
lmsys/vicuna-7b-v1.5
meta-llama/Llama-2-70b-chat-hf
meta-llama/Llama-2-70b-hf
microsoft/phi-2
mistralai/Mistral-7B-Instruct-v0.1
mistralai/Mistral-7B-Instruct-v0.2
mistralai/Mistral-7B-v0.1
mistralai/Mixtral-8x7B-Instruct-v0.1
mistralai/Mixtral-8x7B-v0.1
openchat/openchat-3.5-1210
prompthero/openjourney
runwayml/stable-diffusion-v1-5
snorkelai/Snorkel-Mistral-PairRM-DPO
stabilityai/stable-diffusion-2-1
stabilityai/stable-diffusion-xl-base-1.0
teknium/OpenHermes-2-Mistral-7B
teknium/OpenHermes-2p5-Mistral-7B
togethercomputer/GPT-JT-Moderation-6B
togethercomputer/LLaMA-2-7B-32K
togethercomputer/Llama-2-7B-32K-Instruct
togethercomputer/Qwen-7B-Chat
togethercomputer/Qwen-7B
togethercomputer/RedPajama-INCITE-7B-Base
togethercomputer/RedPajama-INCITE-7B-Chat
togethercomputer/RedPajama-INCITE-7B-Instruct
togethercomputer/RedPajama-INCITE-Base-3B-v1
togethercomputer/RedPajama-INCITE-Chat-3B-v1
togethercomputer/RedPajama-INCITE-Instruct-3B-v1
togethercomputer/StripedHyena-Hessian-7B
togethercomputer/StripedHyena-Nous-7B
togethercomputer/alpaca-7b
togethercomputer/falcon-40b-instruct
togethercomputer/falcon-40b
togethercomputer/falcon-7b-instruct
togethercomputer/falcon-7b
togethercomputer/llama-2-13b-chat
togethercomputer/llama-2-13b
togethercomputer/llama-2-7b-chat
togethercomputer/llama-2-7b
upstage/SOLAR-10.7B-Instruct-v1.0
wavymulder/Analog-Diffusion
zero-one-ai/Yi-34B-Chat
zero-one-ai/Yi-34B
zero-one-ai/Yi-6B
garage-bAInd/Platypus2-70B-instruct
EleutherAI/pythia-1b-v0
replit/replit-code-v1-3b
togethercomputer/Pythia-Chat-Base-7B-v0.16
mosaicml/mpt-7b
togethercomputer/mpt-30b-chat
google/flan-t5-xl
NumbersStation/nsql-6B
togethercomputer/Koala-7B
EleutherAI/pythia-6.9b
databricks/dolly-v2-12b
databricks/dolly-v2-3b
EleutherAI/gpt-neox-20b
EleutherAI/pythia-2.8b-v0
NousResearch/Nous-Hermes-13b
togethercomputer/guanaco-65b
lmsys/fastchat-t5-3b-v1.0
huggyllama/llama-7b
OpenAssistant/stablelm-7b-sft-v7-epoch-3
EleutherAI/pythia-12b-v0
togethercomputer/mpt-7b-chat
EleutherAI/gpt-j-6b
OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5
lmsys/vicuna-7b-v1.3
Phind/Phind-CodeLlama-34B-Python-v1
NumbersStation/nsql-llama-2-7B
NousResearch/Nous-Hermes-Llama2-70b
WizardLM/WizardLM-70B-V1.0
huggyllama/llama-65b
lmsys/vicuna-13b-v1.5-16k
togethercomputer/GPT-NeoXT-Chat-Base-20B
HuggingFaceH4/zephyr-7b-beta
codellama/CodeLlama-34b-hf
togethercomputer/CodeLlama-7b-Instruct
togethercomputer/guanaco-13b
togethercomputer/CodeLlama-34b-Python
mosaicml/mpt-7b-instruct
togethercomputer/llama-2-70b-chat
togethercomputer/CodeLlama-34b-Instruct
togethercomputer/CodeLlama-34b
togethercomputer/CodeLlama-13b-Python
Salesforce/codegen2-16B
Salesforce/codegen2-7B
google/flan-t5-xxl
togethercomputer/llama-2-70b
codellama/CodeLlama-7b-hf
codellama/CodeLlama-13b-hf
togethercomputer/CodeLlama-13b-Instruct
lmsys/vicuna-13b-v1.3
huggyllama/llama-13b
HuggingFaceH4/starchat-alpha
huggyllama/llama-30b
stabilityai/stablelm-base-alpha-3b
stabilityai/stablelm-base-alpha-7b
togethercomputer/CodeLlama-7b-Python
defog/sqlcoder
bigcode/starcoder
databricks/dolly-v2-7b
togethercomputer/guanaco-33b
togethercomputer/Koala-13B
togethercomputer/GPT-JT-6B-v1
togethercomputer/guanaco-7b
EleutherAI/llemma_7b
"""
